In [1]:
raw_d = """.#.##
.###.
##.#.
####.
##.##"""
raw_d = raw_d.split('\n')

import numpy as np
matrix = [[0]*7]
for line in raw_d:
    temp = [0]
    for car in line:
        if car == '.':
            temp.append(0)
        else:
            temp.append(1)
    temp.append(0)
    matrix.append(temp)
matrix.append([0]*7)
matrix = np.matrix(matrix)
matrix2 = np.zeros((7,7))


In [2]:
def checking(y,x):
    return matrix[(y+1,x)]+matrix[(y-1,x)]+matrix[(y,x+1)]+matrix[(y,x-1)]

ss = set()
ss.add(str(matrix))
while True:
    for i in range(1,6):
        for j in range(1,6):
            temp = checking(i,j)
            if matrix[(i,j)] == 1:
                if temp == 1:
                    matrix2[(i,j)] = 1
                else:
                    matrix2[(i,j)] = 0
            if matrix[(i,j)] == 0:
                if temp == 1 or temp == 2:
                    matrix2[(i,j)] = 1
                else:
                    matrix2[(i,j)] = 0
    matrix = matrix2
    if str(matrix) in ss:
        print(matrix)
        break
    else:
        ss.add(str(matrix))
    matrix2 = np.zeros((7,7))

matrix
counter = 0
sol = 0
for i in range(1,6):
    for j in range(1,6):
        if matrix[(i,j)] == 1:
            sol += 2**counter
        counter+=1
    
    
print(sol)        
    

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
19516944


In [3]:
def part2 (coor):
    d,i,j = coor
    temp = set()
    if i == 0:
        temp.add((d+1,1,2))
    elif i == 3 and j == 2:
        for x in range(5):
            temp.add((d-1,4,x))
    else:
        temp.add((d,i-1,j))
    if i == 1 and j == 2:
        for x in range(5):
            temp.add((d-1,0,x))
    elif i == 4:
        temp.add((d+1,3,2))
    else:
        temp.add((d,i+1,j))
    if j == 4:
        temp.add((d+1,2,3))
    elif j == 1 and i == 2:
        for y in range(5):
            temp.add((d-1,y,0))
    else:
        temp.add((d,i,j+1))
    if j == 0:
        temp.add((d+1,2,1))
    elif j == 3 and i == 2:
        for y in range(5):
            temp.add((d-1,y,4))
    else:
        temp.add((d,i,j-1))
    return temp
empty = set()
for d in range(-100,101):
    for i in range(5):
        for j in range(5):
            empty.add((d,i,j))
    empty.remove((d,2,2))
bugs = set()
#a = [(0,0,4),(0,1,0),(0,1,3),(0,2,0),(0,2,3),(0,2,4),(0,3,2),(0,4,0)]

a = [(0,0,1),(0,0,3),(0,0,4),(0,1,1),(0,1,2),(0,1,3),(0,2,0),(0,2,1),(0,2,3),(0,3,0),(0,3,1),(0,3,2),(0,3,3),(0,4,0),(0,4,1),(0,4,3),(0,4,4)]
for item in a:
    bugs.add(item)
    empty.remove(item)

#program
for _ in range(200):
    n_bugs = set()
    n_empty = set()
    for coor in bugs:
        temp = part2(coor)
        counter = 0
        for item in temp:
            if item in bugs:
                counter+=1
        if counter != 1:
            n_empty.add(coor)
        else:
            n_bugs.add(coor)
    for coor in empty:
        temp = part2(coor)
        counter = 0
        for item in temp:
            if item in bugs:
                counter+=1
        if counter == 1 or counter == 2:
            n_bugs.add(coor)
        else:
            n_empty.add(coor)
    bugs = n_bugs
    empty = n_empty
len(n_bugs)       

2006